### ISSUE TITLE
"Adds an additional Arrow" weighted search

### ISSUE THREAD

**Issue by lyrjie** [poeapp/poeapp#141] opened 2017-12-28 11:16 UTC
### Did you clear your browser cache before trying to reproduce?
- [x] Yes

### Did you disable all browser extensions before trying to reproduce?
- [x] Yes

### App Version

2017-12-19T03:46:17.443Z

### Description

With weighted search for "Adds an additional Arrow" mod the items with this mod present don't receive the assigned mod weight. It is probably the case with all non-numeric mods. 

### Expected outcome

Specified weight is added if item has "Adds an additional Arrow" mod.

### Actual outcome

Weight is not added.

### Steps to reproduce

1. Open [this page](https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC5x4BPNNEAGnCjiVU1lQFsAVcgByNIEVEsAG4potejATJ0GNAAswvcaQCa6CWwD2AE2rEA2qG16SoFAA9uWWAGNWGAII69AAjAA7dy9awtHsCxXR2hoLQB3EhhCOggtCECMAGoAYlc41zYwC1g2RDZXABlYADM+AwBGGg9ELCwAXTpuNBREHS1klIBSdPjA3vc61wBRHDYUDwSggCV0WDQEj1sNQyqauvqAX1iePhBwlFg8eQgJaE88cpAATgAGWnWG7eNdfXMrG3sIJxc0dy8wD4IH4AkEQmFIsRoihtiAILsSOAPDoQJstkA)

### Browsers Affected

All of them, it's a server-side issue.
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by poeapp** [comment] 2017-12-28 14:26
Duplicate of https://github.com/poeapp/poeapp/issues/134

**Closed by poeapp** 2017-12-28 14:26 UTC
Labels: duplicate
